travis:
  secure:
    BINSTAR_TOKEN: enFEsEWLUe1e3k7+Y8DIXaemfFGwZ037ZuOKkqjG0uEu/eRWX2O4oblMGdFu1R/3YQvmT576NEGMOwquXF78xhiC2AHd1ciQV39z1KVFLqydjE+qu2PrVoWtU1/obmCAXBgqnzWvKiphuzHR9WtNISUrUoVXYifilZOeD/i2t+hD42g7URV7UIr9H2pMJbemBDiqhBp2FS3t0F1TiVJqZcUEajUQ74kgPOJQX15qkWjJzj1W03cL59fNAwxAuGC7qh3iUWfGnTlXOAWdHTeeH/QPkv/BJk8totKl6yIYwMPripQhhAImb3lR70dOtDmI10RXZfRDZ3fvmmqDIVinWtkdHb/HY+ueQ/f7SZ3hrFo+QlxkLky4Xx0UkI4NmIHmjJV5sNWY07q//UngR9qNbH65vZlapet5BParEpVdV9Xs8ERyz3SDNSzuzJKv+dWn+c1tAydfBI4YHqAslR6CZoPrxr9JPdGVZ1w1sQWCwIOv0zARZU753AnxtlmZ+Io5gQ578zaznjKsfcPBWFCf1Dlt+xXzJTe99lSAOpAxZiHeVTCIbs1ZIXnDWw87DKJaiQUQPb8DrDpTxtdOeI0I7Uw5tdk4v84Hlk+dVEtmMJ3vre6IsTtGvGp7spYhpDSo9GoTnp9op8ggSD/CuHEmyu0meTpGy/D2sGx7vpNia68=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
