appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: N5Olfi3XIZJWwqy9W/F0bGhnXQXAWK7QiyVpNCqRu3+YFBsyClSFOz8o87lFupj3Q31XgNcy9eSBwEu2IXRFtNVyW0uc9/nHJSXeOUP7UxKpTd+mMUeHcu5NeGh6aMYqeR9nphafQwhJAGIcKOOpG2Pgt3qU5S1/ZmUSRm41FMcsg/bjtBTdYmkxMb1I62mVD0VhStKM2kUy4KGaGSVB2DEOqX47kMBIYCDkc/29UTcynBibyB9KRcMvPiielcs335+TVhXJLI1jkIUbKcOaNucjfkElhDR5z+8KXqM4jxsXkYAzCivHG8rnnLpaoHW34Uwmza8dwe5urQbJoSsKoQPMMCLuorDTBMXuYjjE3uOgsx/+BMXjnTFd5QvhxfaTEFvcHYMdU0PhLYHeK4W2MJXfOIS9XF/6KgUZjD5PykPEtHFnDQdKe3uMtaHpEXse5/MUeNY4PkP8ZV1pF4+CFVk1TN+Dv4FBRcgAsfzaidv2oFGRYUYDmIqEXLkuDIqtvGMafkHRmdSo3r5CJazEXYUIOW/UYhiGgZwDaEYR6Ca4FtsfKwam8UIJRPWyHFnVamLlAbiZaY0pmLbBUZ00TKHcqtop3yZfa0U/BXzPZoG1je/jLXX08iP+5KhxT0jg2GQYElNf1N2MfJ6/+apuW92QXQb0xxcSnxZH8R1RCJw=}
